frr version 9.1
frr defaults traditional
hostname br1-edge-01
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.3/32
!
interface eth1
 description to-dc1-core-01
 ip address 10.0.1.2/30
!
interface eth2
 description to-dc1-core-02
 ip address 10.0.2.2/30
!
interface eth3
 description to-br1-acc-01
 ip address 10.2.1.1/30
!
router ospf
 ospf router-id 10.255.255.3
 network 10.255.255.3/32 area 0
 network 10.0.1.0/30 area 0
 network 10.0.2.0/30 area 0
 network 10.2.1.0/30 area 2
!
