frr version 9.1
frr defaults traditional
hostname br1-acc-01
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.7/32
!
interface eth1
 description to-br1-edge-01
 ip address 10.2.1.2/30
!
interface eth2
 description lan-br1-srv-01
 ip address 10.102.1.1/24
!
router ospf
 ospf router-id 10.255.255.7
 network 10.255.255.7/32 area 2
 network 10.2.1.0/30 area 2
 network 10.102.1.0/24 area 2
!
