frr version 9.1
frr defaults traditional
hostname br2-edge-01
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.4/32
!
interface eth1
 description to-dc1-core-01
 ip address 10.0.3.2/30
!
interface eth2
 description to-dc1-core-02
 ip address 10.0.4.2/30
!
interface eth3
 description to-br2-acc-01
 ip address 10.3.1.1/30
!
router ospf
 ospf router-id 10.255.255.4
 network 10.255.255.4/32 area 0
 network 10.0.3.0/30 area 0
 network 10.0.4.0/30 area 0
 network 10.3.1.0/30 area 3
!
