frr version 9.1
frr defaults traditional
hostname dc1-acc-01
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.5/32
!
interface eth1
 description to-dc1-core-01
 ip address 10.1.1.2/30
!
interface eth2
 description to-dc1-core-02
 ip address 10.1.2.2/30
!
router ospf
 ospf router-id 10.255.255.5
 network 10.255.255.5/32 area 1
 network 10.1.1.0/30 area 1
 network 10.1.2.0/30 area 1
!
