frr version 9.1
frr defaults traditional
hostname dc1-core-02
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.2/32
!
interface eth1
 description to-dc1-core-01
 ip address 10.0.0.2/30
!
interface eth2
 description to-br1-edge-01
 ip address 10.0.2.1/30
!
interface eth3
 description to-br2-edge-01
 ip address 10.0.4.1/30
!
interface eth4
 description to-dc1-acc-01
 ip address 10.1.2.1/30
!
interface eth5
 description to-dc1-acc-02
 ip address 10.1.4.1/30
!
router ospf
 ospf router-id 10.255.255.2
 network 10.255.255.2/32 area 0
 network 10.0.0.0/30 area 0
 network 10.0.2.0/30 area 0
 network 10.0.4.0/30 area 0
 network 10.1.2.0/30 area 1
 network 10.1.4.0/30 area 1
!
