frr version 9.1
frr defaults traditional
hostname dc2-core-01
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.9/32
!
interface eth1
 description to-dc2-core-02
 ip address 10.0.5.1/30
!
interface eth2
 description to-dc1-core-01
 ip address 10.0.6.2/30
!
interface eth3
 description to-br1-edge-01
 ip address 10.0.8.1/30
!
interface eth4
 description to-dc2-acc-01
 ip address 10.4.1.1/30
!
router ospf
 ospf router-id 10.255.255.9
 network 10.255.255.9/32 area 0
 network 10.0.5.0/30 area 0
 network 10.0.6.0/30 area 0
 network 10.0.8.0/30 area 0
 network 10.4.1.0/30 area 4
!
