frr version 9.1
frr defaults traditional
hostname dc2-core-02
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.10/32
!
interface eth1
 description to-dc2-core-01
 ip address 10.0.5.2/30
!
interface eth2
 description to-dc1-core-02
 ip address 10.0.7.2/30
!
interface eth3
 description to-br2-edge-01
 ip address 10.0.9.1/30
!
interface eth4
 description to-dc2-acc-01
 ip address 10.4.2.1/30
!
router ospf
 ospf router-id 10.255.255.10
 network 10.255.255.10/32 area 0
 network 10.0.5.0/30 area 0
 network 10.0.7.0/30 area 0
 network 10.0.9.0/30 area 0
 network 10.4.2.0/30 area 4
!
