frr version 9.1
frr defaults traditional
hostname dc2-acc-01
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.11/32
!
interface eth1
 description to-dc2-core-01
 ip address 10.4.1.2/30
!
interface eth2
 description to-dc2-core-02
 ip address 10.4.2.2/30
!
interface eth3
 description lan-dc2-srv-01
 ip address 10.104.1.1/24
!
router ospf
 ospf router-id 10.255.255.11
 network 10.255.255.11/32 area 4
 network 10.4.1.0/30 area 4
 network 10.4.2.0/30 area 4
 network 10.104.1.0/24 area 4
!
