frr version 9.1
frr defaults traditional
hostname lab-r2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.2/32
!
interface eth1
 description to-lab-r1
 ip address 10.0.12.2/30
!
interface eth2
 description to-lab-r3
 ip address 10.0.23.1/30
!
interface eth3
 description to-lab-r4
 ip address 10.0.24.1/30
!
router ospf
 ospf router-id 10.255.255.2
 network 10.0.12.0/30 area 0
 network 10.0.23.0/30 area 0
 network 10.0.24.0/30 area 0
 network 10.255.255.2/32 area 0
!
