frr version 9.1
frr defaults traditional
hostname lab-r4
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.4/32
!
interface eth1
 description to-lab-r1
 ip address 10.0.14.2/30
!
interface eth2
 description to-lab-r2
 ip address 10.0.24.2/30
!
interface eth3
 description to-lab-r3
 ip address 10.0.34.2/30
!
router ospf
 ospf router-id 10.255.255.4
 network 10.0.14.0/30 area 0
 network 10.0.24.0/30 area 0
 network 10.0.34.0/30 area 0
 network 10.255.255.4/32 area 0
!
